name: Renaissance Benchmark

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  benchmark:
    runs-on: ubuntu-latest  # You can specify different OS+JDK combinations here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Choose your desired JDK distribution, e.g., 'adopt' or 'openjdk'
          java-version: '11'  # Specify the Java version

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman  # Install Podman on Ubuntu, adjust for other Linux distributions

      - name: Download Renaissance JAR
        run: |
          wget https://github.com/renaissance-benchmarks/renaissance/releases/download/v0.15.0/renaissance-gpl-0.15.0.jar -O renaissance-gpl-0.15.0.jar
        working-directory: ${{ github.workspace }}

      - name: Debugging - List Working Directory
        run: ls

      - name: Debugging - Check File Existence
        run: test -f renaissance-gpl-0.15.0.jar && echo "File exists" || echo "File does not exist"

      - name: Run Renaissance Benchmarks
        run: |
          podman run -d --name my-jre-container mcr.microsoft.com/openjdk/jdk:21-ubuntu /bin/sleep 30
          podman cp renaissance-gpl-0.15.0.jar my-jre-container:/opt/renaissance-gpl-0.15.0.jar
            # Run diagnostics commands to monitor memory usage
          podman exec my-jre-container /bin/bash -c "top -b -n 1"
          podman exec my-jre-container /bin/bash -c "free -m"
          podman exec my-jre-container /bin/bash -c "vmstat 1 5"
          podman exec my-jre-container /bin/bash -c "ps aux --sort=-%mem | head -n 10"
          podman exec my-jre-container /bin/bash -c "java -Xmx256m -jar /opt/renaissance-gpl-0.15.0.jar future-genetic"
          podman exec my-jre-container /bin/bash -c "java -jar /opt/renaissance-gpl-0.15.0.jar mnemonics"
          podman exec my-jre-container /bin/bash -c "java -jar /opt/renaissance-gpl-0.15.0.jar par-mnemonics"
          podman exec my-jre-container /bin/bash -c "java -jar /opt/renaissance-gpl-0.15.0.jar rx-scrabble"
          podman exec my-jre-container /bin/bash -c "java -jar /opt/renaissance-gpl-0.15.0.jar scrabble"
          podman exec my-jre-container /bin/bash -c "java -jar /opt/renaissance-gpl-0.15.0.jar report"
          podman stop my-jre-container

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: renaissance-report
          path: renaissance/report  # Adjust the path to your report location
